services:
  postgres:
    volumes:
      - postgres:/var/lib/postgresql

  redis:
    volumes:
      - redis:/data

  kafka:
    volumes:
      - kafka:/tmp/kraft-combined-logs

volumes:
  postgres:
  redis:
  kafka:
