apiVersion: 1
policies:
  - orgId: 1
    receiver: Telegram
    group_by: [ "grafana_folder", "alertname" ]
    group_wait: 30s
    group_interval: 1m
    repeat_interval: 4h
    routes:
      - receiver: Telegram
        object_matchers:
          - [ "severity", "=", "error" ]
        group_wait: 1m
        group_interval: 1m
        repeat_interval: 4h
