"""Created tables

Revision ID: 9ea762263fc8
Revises: 
Create Date: 2026-08-02 17:55:01.324658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ea762263fc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_webhook_events',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider', 'event_id')
    )
    op.create_table('discord_access_tokens',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('event_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('standard', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('jwt_token', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_table('billing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('billing_provider', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_provider', 'subscription_id', name='uq_billing_provider_subscription'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notification_channels',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('last_attempted_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id', 'type')
    )
    op.create_table('user_discord_access_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('notification_channel_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_workspaces_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_wallets_workspace_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('fulfilment_type', sa.String(), nullable=False),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name='fk_products_wallet_id'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_products_workspace_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_tokens',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name='fk_wallet_tokens_token_id'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name='fk_wallet_tokens_wallet_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wallet_id', 'token_id')
    )
    op.create_table('prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('recurring_interval', sa.String(), nullable=True),
    sa.Column('recurring_interval_count', sa.Integer(), nullable=True),
    sa.Column('trial_period_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_prices_product_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='fk_prices_merchant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('price_id', sa.UUID(), nullable=False),
    sa.Column('platform_user_id', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], name='fk_transactions_price_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_transactions_product_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('platform_user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('credit_amount', sa.Float(), nullable=False),
    sa.Column('cycle_start', sa.Integer(), nullable=True),
    sa.Column('cycle_end', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_processed_tx', sa.UUID(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_notified_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_processed_tx'], ['transactions.id'], name='fk_subscription_balances_last_processed_tx'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_subscription_balances_product_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'platform_user_id', 'product_id', name='uq_subscription_balances_group_user_product')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_balances')
    op.drop_table('transactions')
    op.drop_table('prices')
    op.drop_table('wallet_tokens')
    op.drop_table('products')
    op.drop_table('wallets')
    op.drop_table('workspaces')
    op.drop_table('user_discord_access_tokens')
    op.drop_table('notification_channels')
    op.drop_table('billing')
    op.drop_table('users')
    op.drop_table('tokens')
    op.drop_table('notifications')
    op.drop_table('event_outbox')
    op.drop_table('discord_access_tokens')
    op.drop_table('billing_webhook_events')
    # ### end Alembic commands ###
