name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Write env file
        uses: JadoreThompson/create-env-file@main
        with:
          filename: .env.test
          content: ${{ secrets.ENV_TEST_FILE }}

      - name: Run tests
        run: uv run pytest

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4.0.0
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_IMAGE }}:latest
            ${{ secrets.DOCKER_REGISTRY_IMAGE }}:${{ github.sha }}
